source 1_set_vars.sql

DELETE from datadictionary where instance=@instance and scope=@scope and entity=@entity;

INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','1','changemo','1a. Date of status change, month','','','1','udsmilestone','CHANGEMO','1','smallint','','1','null','Date of status change, month','1a.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','2','changedy','1b. Date of status change, day','','','1','udsmilestone','CHANGEDY','2','smallint','','1','null','Date of status change, day','1b.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','3','changeyr','1c. Date of status change, year','','','1','udsmilestone','CHANGEYR','3','smallint','','1','null','Date of status change, year','1c.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','4','protocol','2a. UDS data collection status changed; subject''s new status is:','','','1','udsmilestone','PROTOCOL','4','smallint','','1','null','UDS data collection status changed; subject''s new status is:','2a.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','5','aconsent','2a1. Autopsy consent on file?','','','1','udsmilestone','ACONSENT','5','smallint','','1','null','Autopsy consent on file?','2a1.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','6','recogim','2b1. Subject is too cognitively impaired','','','1','udsmilestone','RECOGIM','6','smallint','','1','null','Subject is too cognitively impaired','2b1.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','7','rephyill','2b2. Subject is too ill or physically impaired','','','1','udsmilestone','REPHYILL','7','smallint','','1','null','Subject is too ill or physically impaired','2b2.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','8','rerefuse','2b3. Subject refuses neuropsychological testing or clinical exam','','','1','udsmilestone','REREFUSE','8','smallint','','1','null','Subject refuses neuropsychological testing or clinical exam','2b3.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','9','renavail','2b4. Subject or co-participant unreachable, not available, or moved away','','','1','udsmilestone','RENAVAIL','9','smallint','','1','null','Subject or co-participant unreachable, not available, or moved away','2b4.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','10','renurse','2b5. Subject has permanently entered nursing home','','','1','udsmilestone','RENURSE','10','smallint','','1','null','Subject has permanently entered nursing home','2b5.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','11','nursemo','2b5a. Date permanently moved to nursing home, month','','','1','udsmilestone','NURSEMO','11','smallint','','1','null','Date permanently moved to nursing home, month','2b5a.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','12','nursedy','2b5b. Date permanently moved to nursing home, day','','','1','udsmilestone','NURSEDY','12','smallint','','1','null','Date permanently moved to nursing home, day','2b5b.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','13','nurseyr','2b5c. Date permanently moved to nursing home, year','','','1','udsmilestone','NURSEYR','13','smallint','','1','null','Date permanently moved to nursing home, year','2b5c.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','14','rejoin','2b6. Subject is rejoining ADC','','','1','udsmilestone','REJOIN','14','smallint','','1','null','Subject is rejoining ADC','2b6.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','15','ftlddisc','3. Subject will no longer receive FTLD Module follow-up, but annual in-person UDS visits will continue','','','1','udsmilestone','FTLDDISC','15','smallint','','1','null','Subject will no longer receive FTLD Module follow-up, but annual in-person UDS visits will continue','3.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','16','ftldreas','3a. FTLD discontinued reason','','','1','udsmilestone','FTLDREAS','16','smallint','','1','null','FTLD discontinued reason','3a.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','17','ftldreax','3a1. Other, specify','','','1','udsmilestone','FTLDREAX','17','varchar','60','1','null','Other, specify','3a1.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','18','deceased','4a. Subject has died','','','1','udsmilestone','DECEASED','18','smallint','','1','null','Subject has died','4a.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','19','discont','4b. Subject has been dropped from ADC','','','1','udsmilestone','DISCONT','19','smallint','','1','null','Subject has been dropped from ADC','4b.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','20','deathmo','5a1. Date of death, month','','','1','udsmilestone','DEATHMO','20','smallint','','1','null','Date of death, month','5a1.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','21','deathdy','5a2. Date of death, day','','','1','udsmilestone','DEATHDY','21','smallint','','1','null','Date of death, day','5a2.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','22','deathyr','5a3. Date of death, year','','','1','udsmilestone','DEATHYR','22','smallint','','1','null','Date of death, year','5a3.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','23','autopsy','5b. ADC autopsy','','','1','udsmilestone','AUTOPSY','23','smallint','','1','null','ADC autopsy','5b.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','24','discmo','6a1. Date dropped from ADC, month','','','1','udsmilestone','DISCMO','24','smallint','','1','null','Date dropped from ADC, month','6a1.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','25','discdy','6a2. Date dropped from ADC, day','','','1','udsmilestone','DISCDY','25','smallint','','1','null','Date dropped from ADC, day','6a2.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','26','discyr','6a3. Date dropped from ADC, year','','','1','udsmilestone','DISCYR','26','smallint','','1','null','Date dropped from ADC, year','6a3.');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`,`notes`,`legacy_column`) VALUES ('lava','crms-nacc','udsmilestone3','27','dropreas','6b. Primary reason subject discontinued ADC participation','','','1','udsmilestone','DROPREAS','27','smallint','','1','null','Primary reason subject discontinued ADC participation','6b.');

SELECT concat('use ', @db, ';');
SELECT '';
call util_createtable(@entity,@scope);
SELECT '';
call util_tablekeysadd(@entity,@scope);
SELECT '';
SELECT concat('INSERT IGNORE into instrument(instrname, tablename, formname, hasversion) values(\'', @instrname, '\',\'', 'Multiple', '\',\'LavaWebOnly\',1);');
