use lava_demo;

ALTER TABLE udsmilestone
ADD COLUMN `CHANGEMO` smallint NULL DEFAULT null ,
ADD COLUMN `CHANGEDY` smallint NULL DEFAULT null ,
ADD COLUMN `CHANGEYR` smallint NULL DEFAULT null ,
ADD COLUMN `ACONSENT` smallint NULL DEFAULT null ,
ADD COLUMN `RECOGIM` smallint NULL DEFAULT null ,
ADD COLUMN `REPHYILL` smallint NULL DEFAULT null ,
ADD COLUMN `REREFUSE` smallint NULL DEFAULT null ,
ADD COLUMN `RENAVAIL` smallint NULL DEFAULT null ,
ADD COLUMN `RENURSE` smallint NULL DEFAULT null ,
ADD COLUMN `REJOIN` smallint NULL DEFAULT null ,
ADD COLUMN `FTLDDISC` smallint NULL DEFAULT null ,
ADD COLUMN `FTLDREAS` smallint NULL DEFAULT null ,
ADD COLUMN `FTLDREAX` varchar(60) NULL DEFAULT null ,
ADD COLUMN `DROPREAS` smallint NULL DEFAULT null;