source 1_set_vars.sql

DELETE from datadictionary where instance=@instance and scope=@scope and entity=@entity;

INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','1','cancer','1. Cancer (excluding non-melanoma skin cancer), primary or metastatic','','','1','udsmedicalconditions','CANCER','1','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','2','cancsite','1a. Cancer primary site specification','','','1','udsmedicalconditions','CANCSITE','2','varchar','60','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','3','diabet','2. Diabetes','','','1','udsmedicalconditions','DIABET','3','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','4','myoinf','3. Myocardial infarct','','','1','udsmedicalconditions','MYOINF','4','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','5','conghrt','4. Congestive heart failure','','','1','udsmedicalconditions','CONGHRT','5','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','6','afibrill','5. Atrial fibrillation','','','1','udsmedicalconditions','AFIBRILL','6','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','7','hypert','6. Hypertension','','','1','udsmedicalconditions','HYPERT','7','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','8','angina','7. Angina','','','1','udsmedicalconditions','ANGINA','8','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','9','hypchol','8. Hypercholesterolemia','','','1','udsmedicalconditions','HYPCHOL','9','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','10','vb12def','9. B12 deficiency','','','1','udsmedicalconditions','VB12DEF','10','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','11','thydis','10. Thyroid disease','','','1','udsmedicalconditions','THYDIS','11','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','12','arth','11. Arthritis','','','1','udsmedicalconditions','ARTH','12','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','13','artype','11a. Arthritis type','','','1','udsmedicalconditions','ARTYPE','13','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','14','artypex','11a1. Other arthritis type specification','','','1','udsmedicalconditions','ARTYPEX','14','varchar','60','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','15','artupex','11b1. Arthritis region affected - upper extremity','','','1','udsmedicalconditions','ARTUPEX','15','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','16','artloex','11b2. Arthritis region affected - lower extremity','','','1','udsmedicalconditions','ARTLOEX','16','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','17','artspin','11b3. Arthritis region affected - spine','','','1','udsmedicalconditions','ARTSPIN','17','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','18','artunkn','11b4. Arthritis region affected - unknown','','','1','udsmedicalconditions','ARTUNKN','18','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','19','urineinc','12. Incontinence - urinary','','','1','udsmedicalconditions','URINEINC','19','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','20','bowlinc','13. Incontinence - bowel','','','1','udsmedicalconditions','BOWLINC','20','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','21','sleepap','14. Sleep apnea','','','1','udsmedicalconditions','SLEEPAP','21','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','22','remdis','15. REM sleep behavior disorder (RBD)','','','1','udsmedicalconditions','REMDIS','22','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','23','hyposom','16. Hyposomnia/insomnia','','','1','udsmedicalconditions','HYPOSOM','23','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','24','sleepoth','17. Other sleep disorder','','','1','udsmedicalconditions','SLEEPOTH','24','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','25','sleepotx','17a. Other sleep disorder specification','','','1','udsmedicalconditions','SLEEPOTX','25','varchar','60','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','26','angiocp','18. Carotid procedure: angioplasty, endarterectomy, or stent','','','1','udsmedicalconditions','ANGIOCP','26','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','27','angiopci','19. Percutaneous coronary intervention: angioplasty and/or stent','','','1','udsmedicalconditions','ANGIOPCI','27','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','28','pacemake','20. Procedure: pacemaker and/or defibrillator','','','1','udsmedicalconditions','PACEMAKE','28','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','29','hvalve','21. Procedure: heart valve replacement or repair','','','1','udsmedicalconditions','HVALVE','29','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','30','antienc','22. Antibody-mediated encephalopathy','','','1','udsmedicalconditions','ANTIENC','30','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','31','antiencx','22a. Antibody-mediated encephalopathy, specify','','','1','udsmedicalconditions','ANTIENCX','31','varchar','60','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','32','othcond','23. Other medical conditions or procedures not listed above','','','1','udsmedicalconditions','OTHCOND','32','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsmedicalconditions3','33','othcondx','23a. Other medical conditions specification','','','1','udsmedicalconditions','OTHCONDX','33','varchar','60','1','null');

SELECT concat('use ', @db, ';');
SELECT '';
call util_createtable(@entity,@scope);
SELECT '';
call util_tablekeysadd(@entity,@scope);
SELECT '';
SELECT concat('INSERT IGNORE into instrument(instrname, tablename, formname, hasversion) values(\'', @instrname, '\',\'', 'Multiple', '\',\'LavaWebOnly\',1);');
