
DELETE from viewproperty where instance='lava' and scope='crms-nacc' and entity='udsphoneinclusion3';

INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsphoneinclusion3.cogImp','en','lava','crms-nacc',NULL,'udsphoneinclusion3','cogImp','','r','scale','Yes',NULL,NULL,NULL,NULL,0,'','uds.noYes01',NULL,1,'Why is the UDS telephone follow-up protocol being used to obtain data about the subject? Subject too cognitively impaired for an in-person UDS visit.','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsphoneinclusion3.physImp','en','lava','crms-nacc',NULL,'udsphoneinclusion3','physImp','','r','scale','Yes',NULL,NULL,NULL,NULL,0,'','uds.noYes01',NULL,2,'Why is the UDS telephone follow-up protocol being used to obtain data about the subject? Subject is too physically impaired (medical illness or injury) to attend an in-person UDS visit.','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsphoneinclusion3.home','en','lava','crms-nacc',NULL,'udsphoneinclusion3','home','','r','scale','Yes',NULL,NULL,NULL,NULL,0,'','uds.noYes01',NULL,3,'Why is the UDS telephone follow-up protocol being used to obtain data about the subject? Subject is homebound or in a nursing home and cannot travel.','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsphoneinclusion3.refused','en','lava','crms-nacc',NULL,'udsphoneinclusion3','refused','','r','scale','Yes',NULL,NULL,NULL,NULL,0,'','uds.noYes01',NULL,4,'Why is the UDS telephone follow-up protocol being used to obtain data about the subject? Subject/co-participant refused an in-person UDS visit','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsphoneinclusion3.other','en','lava','crms-nacc',NULL,'udsphoneinclusion3','other','','r','scale','Yes',NULL,NULL,NULL,NULL,0,'','uds.noYes01',NULL,5,'Why is the UDS telephone follow-up protocol being used to obtain data about the subject? Other reason why the UDS telephone follow-up being used','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsphoneinclusion3.otherx','en','lava','crms-nacc',NULL,'udsphoneinclusion3','otherx','','i','string','No',NULL,NULL,NULL,NULL,0,'onkeypress="UDS_onlyNaccCharactersAllowed(event)"',NULL,NULL,6,'Why is the UDS telephone follow-up protocol being used to obtain data about the subject? Other reason specification: (ADC staff convenience is not an acceptable reason.)','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsphoneinclusion3.inperson','en','lava','crms-nacc',NULL,'udsphoneinclusion3','inperson','','r','scale','Yes',NULL,NULL,NULL,NULL,0,'','uds.noYesUnknown019',NULL,7,'Is the subject likely to resume in-person UDS follow-up evaluation?','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsphoneinclusion3.milestone','en','lava','crms-nacc',NULL,'udsphoneinclusion3','milestone','','r','scale','Yes',NULL,NULL,NULL,NULL,0,'','uds.noYesUnknown019',NULL,8,'Has a Milestones Form documenting the change to telephone follow-up been completed? (If No, complete a Milestone Form now.)','2009-01-24 21:28:51');
