-- the 'strength' fields of medications version 1 must be INT, not SMALLINT, to account for max value 99999
ALTER TABLE `udsmedicationspre1`
  MODIFY COLUMN `PMAS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMBS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMCS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMDS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMES` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMFS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMGS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMHS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMIS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMJS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMKS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMLS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMMS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMNS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMOS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMPS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMQS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMRS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMSS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `PMTS` INT(5) DEFAULT NULL;
ALTER TABLE `udsmedicationsnon1`
  MODIFY COLUMN `NMAS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMBS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMCS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMDS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMES` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMFS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMGS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMHS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMIS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMJS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMKS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMLS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMMS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMNS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMOS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMPS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMQS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMRS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMSS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `NMTS` INT(5) DEFAULT NULL;
ALTER TABLE `udsmedicationsvit1`
  MODIFY COLUMN `VSAS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSBS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSCS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSDS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSES` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSFS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSGS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSHS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSIS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSJS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSKS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSLS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSMS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSNS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSOS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSPS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSQS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSRS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSSS` INT(5) DEFAULT NULL,
  MODIFY COLUMN `VSTS` INT(5) DEFAULT NULL;
  
  
  -- ensure view only allows NACC-accepted characters for submitted string fields                                                                         
--   (at the time, there are 321 such viewproperty rows getting updated)                                                                                
UPDATE viewproperty v
  SET attributes='onkeypress="UDS_onlyNaccCharactersAllowed(event)"'
WHERE style = 'string'
  AND scope='crms-nacc'
  -- udsmedications2 string fields are not submitted; I don't know requirements for NaccPathology and MdsStatus                                         
  AND entity NOT IN ('naccpathology9', 'mdsstatus', 'udsmedications2')
  -- the only udsinstrument "common" string field that is submitted is initials                                                                         
  AND (entity != 'udsinstrument' OR property='initials')
  -- at this point, either `attributes` is empty or set to use the onlyNumsAllowed() event, which is even more picky                                    
  AND (attributes IS NULL OR attributes = '');


ALTER TABLE `udsformchecklist` MODIFY COLUMN `A2COMM` VARCHAR(60) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
 MODIFY COLUMN `A3COMM` VARCHAR(60) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
 MODIFY COLUMN `A4COMM` VARCHAR(60) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
 MODIFY COLUMN `B1COMM` VARCHAR(60) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
 MODIFY COLUMN `B2COMM` VARCHAR(60) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
 MODIFY COLUMN `B3COMM` VARCHAR(60) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
 MODIFY COLUMN `B5COMM` VARCHAR(60) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
 MODIFY COLUMN `B6COMM` VARCHAR(60) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
 MODIFY COLUMN `B7COMM` VARCHAR(60) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
 MODIFY COLUMN `B8COMM` VARCHAR(60) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL;


  
  