INSERT INTO `listvalues` (`ListID`,instance,scope,`ValueKey`,`ValueDesc`,`OrderID`,`modified`) SELECT `ListID`,'lava','crms-nacc','naccpathology','10',2,NOW() FROM `list` where `ListName`='InstrumentVersions';
/*Update NACC Pathology to version 10*/
ALTER TABLE naccpathology
ADD COLUMN NPPMIH decimal(4,1) NULL,
ADD COLUMN NPFIX smallint NULL,
ADD COLUMN NPFIXX varchar(30) NULL,
ADD COLUMN NPWBRWT smallint NULL,
ADD COLUMN NPWBRF smallint NULL,
ADD COLUMN NPGRCCA smallint NULL,
ADD COLUMN NPGRLA smallint NULL,
ADD COLUMN NPGRHA smallint NULL,
ADD COLUMN NPGRSNH smallint NULL,
ADD COLUMN NPGRLCH smallint NULL,
ADD COLUMN NPTAN smallint NULL,
ADD COLUMN NPTANX varchar(30) NULL,
ADD COLUMN NPABAN smallint NULL,
ADD COLUMN NPABANX varchar(30) NULL,
ADD COLUMN NPASAN smallint NULL,
ADD COLUMN NPASANX varchar(30) NULL,
ADD COLUMN NPTDPAN smallint NULL,
ADD COLUMN NPTDPANX varchar(30) NULL,
ADD COLUMN NPHISMB smallint NULL,
ADD COLUMN NPHISG smallint NULL,
ADD COLUMN NPHISSS smallint NULL,
ADD COLUMN NPHIST smallint NULL,
ADD COLUMN NPHISO smallint NULL,
ADD COLUMN NPHISOX varchar(30) NULL,
ADD COLUMN NPTHAL smallint NULL,
ADD COLUMN NPADNC smallint NULL,
ADD COLUMN NPINF smallint NULL,
ADD COLUMN NPINF1A smallint NULL,
ADD COLUMN NPINF1B decimal(3,1) NULL,
ADD COLUMN NPINF1D decimal(3,1) NULL,
ADD COLUMN NPINF1F decimal(3,1) NULL,
ADD COLUMN NPINF2A smallint NULL,
ADD COLUMN NPINF2B decimal(3,1) NULL,
ADD COLUMN NPINF2D decimal(3,1) NULL,
ADD COLUMN NPINF2F decimal(3,1) NULL,
ADD COLUMN NPINF3A smallint NULL,
ADD COLUMN NPINF3B decimal(3,1) NULL,
ADD COLUMN NPINF3D decimal(3,1) NULL,
ADD COLUMN NPINF3F decimal(3,1) NULL,
ADD COLUMN NPINF4A smallint NULL,
ADD COLUMN NPINF4B decimal(3,1) NULL,
ADD COLUMN NPINF4D decimal(3,1) NULL,
ADD COLUMN NPINF4F decimal(3,1) NULL,
ADD COLUMN NPHEMO smallint NULL,
ADD COLUMN NPHEMO1 smallint NULL,
ADD COLUMN NPHEMO2 smallint NULL,
ADD COLUMN NPHEMO3 smallint NULL,
ADD COLUMN NPOLD smallint NULL,
ADD COLUMN NPOLD1 smallint NULL,
ADD COLUMN NPOLD2 smallint NULL,
ADD COLUMN NPOLD3 smallint NULL,
ADD COLUMN NPOLD4 smallint NULL,
ADD COLUMN NPOLDD smallint NULL,
ADD COLUMN NPOLDD1 smallint NULL,
ADD COLUMN NPOLDD2 smallint NULL,
ADD COLUMN NPOLDD3 smallint NULL,
ADD COLUMN NPOLDD4 smallint NULL,
ADD COLUMN NPWMR smallint NULL,
ADD COLUMN NPPATH smallint NULL,
ADD COLUMN NPPATH2 smallint NULL,
ADD COLUMN NPPATH3 smallint NULL,
ADD COLUMN NPPATH4 smallint NULL,
ADD COLUMN NPPATH5 smallint NULL,
ADD COLUMN NPPATH6 smallint NULL,
ADD COLUMN NPPATH7 smallint NULL,
ADD COLUMN NPPATH8 smallint NULL,
ADD COLUMN NPPATH9 smallint NULL,
ADD COLUMN NPPATH10 smallint NULL,
ADD COLUMN NPPATH11 smallint NULL,
ADD COLUMN NPPATHO smallint NULL,
ADD COLUMN NPPATHOX varchar(30) NULL,
ADD COLUMN NPLBOD smallint NULL,
ADD COLUMN NPNLOSS smallint NULL,
ADD COLUMN NPHIPSCL smallint NULL,
ADD COLUMN NPTDPA smallint NULL,
ADD COLUMN NPTDPB smallint NULL,
ADD COLUMN NPTDPC smallint NULL,
ADD COLUMN NPTDPD smallint NULL,
ADD COLUMN NPTDPE smallint NULL,
ADD COLUMN NPFTDTAU smallint NULL,
ADD COLUMN NPFTDT2 smallint NULL,
ADD COLUMN NPFTDT5 smallint NULL,
ADD COLUMN NPFTDT6 smallint NULL,
ADD COLUMN NPFTDT7 smallint NULL,
ADD COLUMN NPFTDT8 smallint NULL,
ADD COLUMN NPFTDT9 smallint NULL,
ADD COLUMN NPFTDT10 smallint NULL,
ADD COLUMN NPFTDTDP smallint NULL,
ADD COLUMN NPALSMND smallint NULL,
ADD COLUMN NPOFTD smallint NULL,
ADD COLUMN NPOFTD1 smallint NULL,
ADD COLUMN NPOFTD2 smallint NULL,
ADD COLUMN NPOFTD3 smallint NULL,
ADD COLUMN NPOFTD4 smallint NULL,
ADD COLUMN NPOFTD5 smallint NULL,
ADD COLUMN NPPDXA smallint NULL,
ADD COLUMN NPPDXB smallint NULL,
ADD COLUMN NPPDXC smallint NULL,
ADD COLUMN NPPDXD smallint NULL,
ADD COLUMN NPPDXE smallint NULL,
ADD COLUMN NPPDXF smallint NULL,
ADD COLUMN NPPDXG smallint NULL,
ADD COLUMN NPPDXH smallint NULL,
ADD COLUMN NPPDXI smallint NULL,
ADD COLUMN NPPDXJ smallint NULL,
ADD COLUMN NPPDXK smallint NULL,
ADD COLUMN NPPDXL smallint NULL,
ADD COLUMN NPPDXM smallint NULL,
ADD COLUMN NPPDXN smallint NULL,
ADD COLUMN NPPDXO smallint NULL,
ADD COLUMN NPPDXP smallint NULL,
ADD COLUMN NPPDXQ smallint NULL,
ADD COLUMN NPPDXR smallint NULL,
ADD COLUMN NPPDXRX varchar(30) NULL,
ADD COLUMN NPPDXS smallint NULL,
ADD COLUMN NPPDXSX varchar(30) NULL,
ADD COLUMN NPPDXT smallint NULL,
ADD COLUMN NPPDXTX varchar(30) NULL,
ADD COLUMN NPBNKA smallint NULL,
ADD COLUMN NPBNKB smallint NULL,
ADD COLUMN NPBNKC smallint NULL,
ADD COLUMN NPBNKD smallint NULL,
ADD COLUMN NPBNKE smallint NULL,
ADD COLUMN NPBNKF smallint NULL,
ADD COLUMN NPBNKG smallint NULL,
ADD COLUMN NPFAUT smallint NULL,
ADD COLUMN NPFAUT1 varchar(60) NULL,
ADD COLUMN NPFAUT2 varchar(60) NULL,
ADD COLUMN NPFAUT3 varchar(60) NULL,
ADD COLUMN NPFAUT4 varchar(60) NULL;

-- --------------------------------------------------------------------------------
-- Update naccpathology change version proc
-- --------------------------------------------------------------------------------
DROP PROCEDURE IF EXISTS `proc_naccpathology_change_version`;
 
DELIMITER $$

CREATE PROCEDURE `proc_naccpathology_change_version`(instrument_id INT, new_version VARCHAR(25))
BEGIN

DECLARE existing_version VARCHAR(25);

SELECT `InstrVer` INTO existing_version FROM `instrumenttracking` WHERE `InstrID`=instrument_id;
IF existing_version <> new_version THEN 
	UPDATE `instrumenttracking` SET `InstrVer`= new_version WHERE `InstrID`=instrument_id;
	UPDATE `udstracking` SET `FormVer`= new_version WHERE `InstrID`=instrument_id;
	UPDATE naccpathology SET npgross=CASE WHEN new_version = '10' THEN -8 WHEN new_version = '9' THEN NULL END,
	npnit=CASE WHEN new_version='10' THEN -8  WHEN new_version = '9' THEN NULL END,
npcerad=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npadrda=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npocrit=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npbraak=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npneur=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npdiff=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npvasc=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nplinf=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npmicro=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nplac=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nphem=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npart=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npnec=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npscl=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npavas=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nparter=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npamy=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npoang=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npvoth=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nplewy=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nplewycs=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nppick=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npcort=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npprog=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npfront=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nptau=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npftd=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npftdno=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npftdspc=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npcj=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npprion=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npmajor=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npgene=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npapoe=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nptauhap=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npprnp=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npchrom=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nppnorm=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npcnorm=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nppadp=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npcadp=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nppad=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npcad=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npplewy=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npclewy=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nppvasc=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npcvasc=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nppftld=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npcftld=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npphipp=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npchipp=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nppprion=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npcprion=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nppoth1=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npcoth1=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nppoth2=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npcoth2=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
nppoth3=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npcoth3=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npbrfrzn=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npbrfrm=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npbparf=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,
npcsfant=CASE WHEN new_version = '10' THEN -8  WHEN new_version = '9' THEN NULL END,

nppmih=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npfix=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npfixx=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npwbrwt=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npwbrf=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npgrcca=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npgrla=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npgrha=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npgrsnh=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npgrlch=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npavas=CASE WHEN new_version = '9' THEN NULL WHEN new_version = '10' THEN NULL END,
nptan=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nptanx=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npaban=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npabanx=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npasan=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npasanx=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nptdpan=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nptdpanx=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nphismb=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nphisg=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nphisss=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nphist=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nphiso=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nphisox=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npthal=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npbraak=CASE WHEN new_version = '9' THEN NULL  WHEN new_version = '10' THEN NULL END,
npneur=CASE WHEN new_version = '9' THEN NULL  WHEN new_version = '10' THEN NULL END,
npadnc=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npdiff=CASE WHEN new_version = '9' THEN NULL  WHEN new_version = '10' THEN NULL END,
npamy=CASE WHEN new_version = '9' THEN NULL  WHEN new_version = '10' THEN NULL END,
npinf=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf1a=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf1b=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf1d=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf1f=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf2a=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf2b=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf2d=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf2f=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf3a=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf3b=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf3d=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf3f=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf4a=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf4b=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf4d=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npinf4f=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nphemo=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nphemo1=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nphemo2=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nphemo3=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npold=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npold1=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npold2=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npold3=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npold4=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npoldd=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npoldd1=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npoldd2=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npoldd3=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npoldd4=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nparter=CASE WHEN new_version = '9' THEN NULL  WHEN new_version = '10' THEN NULL END,
npwmr=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppath=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npnec=CASE WHEN new_version = '9' THEN NULL WHEN new_version = '10' THEN NULL END,
nppath2=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppath3=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppath4=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppath5=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppath6=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppath7=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppath8=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppath9=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppath10=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppath11=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppatho=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppathox=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nplbod=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npnloss=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nphipscl=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nptdpa=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nptdpb=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nptdpc=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nptdpd=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nptdpe=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npftdtau=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppick=CASE WHEN new_version = '9' THEN NULL  WHEN new_version = '10' THEN NULL END,
npftdt2=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npcort=CASE WHEN new_version = '9' THEN NULL  WHEN new_version = '10' THEN NULL END,
npprog=CASE WHEN new_version = '9' THEN NULL  WHEN new_version = '10' THEN NULL END,
npftdt5=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npftdt6=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npftdt7=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npftdt8=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npftdt9=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npftdt10=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npftdtdp=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npalsmnd=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npoftd=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npoftd1=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npoftd2=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npoftd3=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npoftd4=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npoftd5=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxa=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxb=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxc=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxd=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxe=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxf=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxg=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxh=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxi=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxj=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxk=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxl=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxm=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxn=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxo=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxp=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxq=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxr=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxrx=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxs=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxsx=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxt=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
nppdxtx=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npbnka=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npbnkb=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npbnkc=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npbnkd=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npbnke=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npbnkf=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npbnkg=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npfaut=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npfaut1=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npfaut2=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npfaut3=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END,
npfaut4=CASE WHEN new_version = '9' THEN -8  WHEN new_version = '10' THEN NULL END
WHERE InstrID=instrument_id;
END IF;
END $$



INSERT INTO versionhistory(module,version,versiondate,major,minor,fix,updaterequired)
VALUES ('lava-crms-nacc-model','3.5.0','2014-03-07',3,5,0,1);
 