use lava_demo;

DROP TABLE IF EXISTS `udsneuropsychmoca`;
CREATE TABLE IF NOT EXISTS `udsneuropsychmoca` (
  `InstrID` INT NOT NULL ,
  `MOCACOMP` smallint NULL DEFAULT null ,
  `MOCAREAS` smallint NULL DEFAULT null ,
  `MOCALOC` smallint NULL DEFAULT null ,
  `MOCALAN` smallint NULL DEFAULT null ,
  `MOCALANX` varchar(60) NULL DEFAULT null ,
  `MOCAVIS` smallint NULL DEFAULT null ,
  `MOCAHEAR` smallint NULL DEFAULT null ,
  `MOCATOTS` smallint NULL DEFAULT null ,
  `MOCATRAI` smallint NULL DEFAULT null ,
  `MOCACUBE` smallint NULL DEFAULT null ,
  `MOCACLOC` smallint NULL DEFAULT null ,
  `MOCACLON` smallint NULL DEFAULT null ,
  `MOCACLOH` smallint NULL DEFAULT null ,
  `MOCANAMI` smallint NULL DEFAULT null ,
  `MOCAREGI` smallint NULL DEFAULT null ,
  `MOCADIGI` smallint NULL DEFAULT null ,
  `MOCALETT` smallint NULL DEFAULT null ,
  `MOCASER7` smallint NULL DEFAULT null ,
  `MOCAREPE` smallint NULL DEFAULT null ,
  `MOCAFLUE` smallint NULL DEFAULT null ,
  `MOCAABST` smallint NULL DEFAULT null ,
  `MOCARECN` smallint NULL DEFAULT null ,
  `MOCARECC` smallint NULL DEFAULT null ,
  `MOCARECR` smallint NULL DEFAULT null ,
  `MOCAORDT` smallint NULL DEFAULT null ,
  `MOCAORMO` smallint NULL DEFAULT null ,
  `MOCAORYR` smallint NULL DEFAULT null ,
  `MOCAORDY` smallint NULL DEFAULT null ,
  `MOCAORPL` smallint NULL DEFAULT null ,
  `MOCAORCT` smallint NULL DEFAULT null ,
  `NPSYCLOC` smallint NULL DEFAULT null ,
  `NPSYLAN` smallint NULL DEFAULT null ,
  `NPSYLANX` varchar(60) NULL DEFAULT null ,
  `CRAFTVRS` smallint NULL DEFAULT null ,
  `CRAFTURS` smallint NULL DEFAULT null ,
  `UDSBENTC` smallint NULL DEFAULT null ,
  `DIGFORCT` smallint NULL DEFAULT null ,
  `DIGFORSL` smallint NULL DEFAULT null ,
  `DIGBACCT` smallint NULL DEFAULT null ,
  `DIGBACLS` smallint NULL DEFAULT null ,
  `ANIMALS` smallint NULL DEFAULT null ,
  `VEG` smallint NULL DEFAULT null ,
  `TRAILA` smallint NULL DEFAULT null ,
  `TRAILARR` smallint NULL DEFAULT null ,
  `TRAILALI` smallint NULL DEFAULT null ,
  `TRAILB` smallint NULL DEFAULT null ,
  `TRAILBRR` smallint NULL DEFAULT null ,
  `TRAILBLI` smallint NULL DEFAULT null ,
  `CRAFTDVR` smallint NULL DEFAULT null ,
  `CRAFTDRE` smallint NULL DEFAULT null ,
  `CRAFTDTI` smallint NULL DEFAULT null ,
  `CRAFTCUE` smallint NULL DEFAULT null ,
  `UDSBENTD` smallint NULL DEFAULT null ,
  `UDSBENRS` smallint NULL DEFAULT null ,
  `MINTTOTS` smallint NULL DEFAULT null ,
  `MINTTOTW` smallint NULL DEFAULT null ,
  `MINTSCNG` smallint NULL DEFAULT null ,
  `MINTSCNC` smallint NULL DEFAULT null ,
  `MINTPCNG` smallint NULL DEFAULT null ,
  `MINTPCNC` smallint NULL DEFAULT null ,
  `UDSVERFC` smallint NULL DEFAULT null ,
  `UDSVERFN` smallint NULL DEFAULT null ,
  `UDSVERNF` smallint NULL DEFAULT null ,
  `UDSVERLC` smallint NULL DEFAULT null ,
  `UDSVERLR` smallint NULL DEFAULT null ,
  `UDSVERLN` smallint NULL DEFAULT null ,
  `UDSVERTN` smallint NULL DEFAULT null ,
  `UDSVERTE` smallint NULL DEFAULT null ,
  `UDSVERTI` smallint NULL DEFAULT null ,
  `COGSTAT` smallint NULL DEFAULT null ,
  PRIMARY KEY (`InstrID`) )
ENGINE = InnoDB;

ALTER TABLE `udsneuropsychmoca` ADD CONSTRAINT `udsneuropsychmoca__InstrID`
 FOREIGN KEY (`InstrID` )
 REFERENCES `instrumenttracking` (`InstrID`)
 ON DELETE NO ACTION
 ON UPDATE NO ACTION, ADD INDEX `udsneuropsychmoca__InstrID` (`InstrID` ASC);

INSERT IGNORE into instrument(instrname, tablename, formname, hasversion) values('UDS Neuropsych Moca','Multiple','LavaWebOnly',1);
