# -*- coding: utf-8 -*-
from pylava.core.column import *
from pylava.core.instrument import *
fullname='UDS Family History 3'
jname='UDSFamilyHistory3'
tname='udsfamilyhistory3'

udscode='A3'

FADMUT_list = NumericRangeUds('uds3.udsfamilyhistory3.FADMUT',
                        odict([
                           (0,'No'),
                           (1,'Yes, APP'),
                           (2,'Yes, PS-1 (PSEN-1)'),
                           (3,'Yes, PS-2 (PSEN-2)'),
                           (8,'Yes, Other (specify)'),
                           (9,'Unknown whether mutation exists'),
                        ])
    )


FADMUSO_list = NumericRangeUds('uds3.udsfamilyhistory3.FADMUSO',
                        odict([
                           (1,'Family report (no test documentation available)'),
                           (2,'Commercial test documentation'),
                           (3,'Research lab test documentation'),
                           (8,'Other (specify)'),
                           (9,'Unknown'),
                        ])
    )


FFTDMUT_list = NumericRangeUds('uds3.udsfamilyhistory3.FFTDMUT',
                        odict([
                           (0,'No'),
                           (1,'Yes, MAPT'),
                           (2,'Yes, PGRN'),
                           (3,'Yes, C9orf72'),
                           (4,'Yes, FUS'),
                           (8,'Yes, Other (specify)'),
                           (9,'Unknown whether mutation exists'),
                        ])
    )


FOTHMUT_list = NumericRangeUds('uds3.udsfamilyhistory3.FOTHMUT',
                        odict([
                           (0,'No'),
                           (1,'Yes (specify)'),
                           (9,'Unknown'),
                        ])
    )


DECAGE_list = NumericRangeUds('uds3.udsfamilyhistory3.DECAGE',
                        odict([
                           (888,'N/A'),
                           (999,'Unknown'),
                        ]),
                    minimum=15 ,
                    maximum=110 
    )


NEURPROB_list = NumericRangeUds('uds3.udsfamilyhistory3.NEURPROB',
                        odict([
                           (1,'Cognitive impairment/behavior change'),
                           (2,'Parkinsonism'),
                           (3,'ALS'),
                           (4,'Other neurologic condition such as multiple sclerosis or stroke'),
                           (5,'Psychiatric condition such as schizophrenia, bipolar disorder, or alcoholism'),
                           (8,'N/A, no neurological problem or psychiatric condition'),
                           (9,'Unknown'),
                        ])
    )


PrimDx_list = NumericRangeUds('uds3.udsfamilyhistory3.PrimDx',
                        odict([
                           (999,'Unknown'),
                        ]),
                    minimum=40 ,
                    maximum=490 
    )


EvalMethod_list = NumericRangeUds('uds3.udsfamilyhistory3.EvalMethod',
                        odict([
                           (1,'Autopsy'),
                           (2,'Examination'),
                           (3,'Medical record review from formal dementia evaluation'),
                           (4,'Review of general medical records AND co-participant and/or subject telephone interview'),
                           (5,'Review of general medical records only'),
                           (6,'Subject and/or co-participant telephone interview'),
                           (7,'Family report'),
                        ])
    )


FamAge_list = NumericRangeUds('uds3.udsfamilyhistory3.FamAge',
                        odict([
                           (999,'Unknown'),
                        ]),
                    minimum=15 ,
                    maximum=110 
    )

SIBS_list = NumericRangeUds('uds3.udsfamilyhistory3.SIBS',
                    maximum=20 
    )

FamYOB_list = NumericRangeUds('uds3.udsfamilyhistory3.FamYOB',
                        odict([
                           (9999,'Unknown'),
                        ]),
                    minimum=1875 ,
                    maximum=2015 
    )

FamYOB2_list = NumericRangeUds('uds3.udsfamilyhistory3.FamYOB2',
                        odict([
                           (9999,'Unknown'),
                        ]),
                    minimum=1910 ,
                    maximum=2015 
    )

columns=[
    Choice("AFFFAMM","Are there affected first-degree relatives?",listname="list.uds3.common.noyesunknown"),
    Choice("FADMUT","In this family, is there evidence for an AD mutation? If Yes, select predominant mutation.",lavalist=FADMUT_list),
    VarChar("FADMUTX","If Yes, Other (specify)",60),
    Choice("FADMUSO","Source of evidence for AD mutation",lavalist=FADMUSO_list),
    VarChar("FADMUSOX","If other, specify",60),
    Choice("FFTDMUT","In this family, is there evidence for an FTLD mutation? If Yes, select predominant mutation.",lavalist=FFTDMUT_list),
    VarChar("FFTDMUTX","If Yes, Other (specify)",60),
    Choice("FFTDMUSO","Source of evidence for FTLD mutation",lavalist=FADMUSO_list),
    VarChar("FFTDMUSX","If other, specify",60),
    Choice("FOTHMUT","In this family, is there evidence for a mutation other than an AD or FTLD mutation?",lavalist=FOTHMUT_list),
    VarChar("FOTHMUTX","If Yes, specify",60),
    Choice("FOTHMUSO","Source of evidence for other mutation:",lavalist=FADMUSO_list),
    VarChar("FOTHMUSX","If other, specify:",60),
    Choice("MOMMOB","Mother — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("MOMYOB","Mother — Birth year",lavalist=FamYOB_list),
    Choice("MOMDAGE","Mother — Age at death",lavalist=DECAGE_list),
    Choice("MOMNEUR","Mother — Neurological problem",lavalist=NEURPROB_list),
    Choice("MOMPRDX","Mother — Primary diagnosis",lavalist=PrimDx_list),
    Choice("MOMMOE","Mother — Method of evaluation",lavalist=EvalMethod_list),
    Choice("MOMAGEO","Mother — Age of onset",lavalist=FamAge_list),
    Choice("DADMOB","Mother — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("DADYOB","Mother — Birth year",lavalist=FamYOB_list),
    Choice("DADDAGE","Mother — Age at death",lavalist=DECAGE_list),
    Choice("DADNEUR","Mother — Neurological problem",lavalist=NEURPROB_list),
    Choice("DADPRDX","Mother — Primary diagnosis",lavalist=PrimDx_list),
    Choice("DADMOE","Mother — Method of evaluation",lavalist=EvalMethod_list),
    Choice("DADAGEO","Mother — Age of onset",lavalist=FamAge_list),
    Choice("SIBS","Number of full siblings?",lavalist=SIBS_list),
    Choice("SIB1MOB","Sibling 1 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB1YOB","Sibling 1 — Birth year",lavalist=FamYOB_list),
    Choice("SIB1AGD","Sibling 1 — Age at death",lavalist=DECAGE_list),
    Choice("SIB1NEU","Sibling 1 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB1PDX","Sibling 1 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB1MOE","Sibling 1 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB1AGO","Sibling 1 — Age of onset",lavalist=FamAge_list),
    Choice("SIB2MOB","Sibling 2 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB2YOB","Sibling 2 — Birth year",lavalist=FamYOB_list),
    Choice("SIB2AGD","Sibling 2 — Age at death",lavalist=DECAGE_list),
    Choice("SIB2NEU","Sibling 2 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB2PDX","Sibling 2 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB2MOE","Sibling 2 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB2AGO","Sibling 2 — Age of onset",lavalist=FamAge_list),
    Choice("SIB3MOB","Sibling 3 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB3YOB","Sibling 3 — Birth year",lavalist=FamYOB_list),
    Choice("SIB3AGD","Sibling 3 — Age at death",lavalist=DECAGE_list),
    Choice("SIB3NEU","Sibling 3 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB3PDX","Sibling 3 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB3MOE","Sibling 3 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB3AGO","Sibling 3 — Age of onset",lavalist=FamAge_list),
    Choice("SIB4MOB","Sibling 4 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB4YOB","Sibling 4 — Birth year",lavalist=FamYOB_list),
    Choice("SIB4AGD","Sibling 4 — Age at death",lavalist=DECAGE_list),
    Choice("SIB4NEU","Sibling 4 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB4PDX","Sibling 4 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB4MOE","Sibling 4 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB4AGO","Sibling 4 — Age of onset",lavalist=FamAge_list),
    Choice("SIB5MOB","Sibling 5 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB5YOB","Sibling 5 — Birth year",lavalist=FamYOB_list),
    Choice("SIB5AGD","Sibling 5 — Age at death",lavalist=DECAGE_list),
    Choice("SIB5NEU","Sibling 5 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB5PDX","Sibling 5 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB5MOE","Sibling 5 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB5AGO","Sibling 5 — Age of onset",lavalist=FamAge_list),
    Choice("SIB6MOB","Sibling 6 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB6YOB","Sibling 6 — Birth year",lavalist=FamYOB_list),
    Choice("SIB6AGD","Sibling 6 — Age at death",lavalist=DECAGE_list),
    Choice("SIB6NEU","Sibling 6 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB6PDX","Sibling 6 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB6MOE","Sibling 6 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB6AGO","Sibling 6 — Age of onset",lavalist=FamAge_list),
    Choice("SIB7MOB","Sibling 7 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB7YOB","Sibling 7 — Birth year",lavalist=FamYOB_list),
    Choice("SIB7AGD","Sibling 7 — Age at death",lavalist=DECAGE_list),
    Choice("SIB7NEU","Sibling 7 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB7PDX","Sibling 7 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB7MOE","Sibling 7 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB7AGO","Sibling 7 — Age of onset",lavalist=FamAge_list),
    Choice("SIB8MOB","Sibling 8 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB8YOB","Sibling 8 — Birth year",lavalist=FamYOB_list),
    Choice("SIB8AGD","Sibling 8 — Age at death",lavalist=DECAGE_list),
    Choice("SIB8NEU","Sibling 8 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB8PDX","Sibling 8 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB8MOE","Sibling 8 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB8AGO","Sibling 8 — Age of onset",lavalist=FamAge_list),
    Choice("SIB9MOB","Sibling 9 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB9YOB","Sibling 9 — Birth year",lavalist=FamYOB_list),
    Choice("SIB9AGD","Sibling 9 — Age at death",lavalist=DECAGE_list),
    Choice("SIB9NEU","Sibling 9 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB9PDX","Sibling 9 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB9MOE","Sibling 9 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB9AGO","Sibling 9 — Age of onset",lavalist=FamAge_list),
    Choice("SIB10MOB","Sibling 10 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB10YOB","Sibling 10 — Birth year",lavalist=FamYOB_list),
    Choice("SIB10AGD","Sibling 10 — Age at death",lavalist=DECAGE_list),
    Choice("SIB10NEU","Sibling 10 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB10PDX","Sibling 10 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB10MOE","Sibling 10 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB10AGO","Sibling 10 — Age of onset",lavalist=FamAge_list),
    Choice("SIB11MOB","Sibling 11 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB11YOB","Sibling 11 — Birth year",lavalist=FamYOB_list),
    Choice("SIB11AGD","Sibling 11 — Age at death",lavalist=DECAGE_list),
    Choice("SIB11NEU","Sibling 11 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB11PDX","Sibling 11 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB11MOE","Sibling 11 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB11AGO","Sibling 11 — Age of onset",lavalist=FamAge_list),
    Choice("SIB12MOB","Sibling 12 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB12YOB","Sibling 12 — Birth year",lavalist=FamYOB_list),
    Choice("SIB12AGD","Sibling 12 — Age at death",lavalist=DECAGE_list),
    Choice("SIB12NEU","Sibling 12 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB12PDX","Sibling 12 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB12MOE","Sibling 12 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB12AGO","Sibling 12 — Age of onset",lavalist=FamAge_list),
    Choice("SIB13MOB","Sibling 13 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB13YOB","Sibling 13 — Birth year",lavalist=FamYOB_list),
    Choice("SIB13AGD","Sibling 13 — Age at death",lavalist=DECAGE_list),
    Choice("SIB13NEU","Sibling 13 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB13PDX","Sibling 13 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB13MOE","Sibling 13 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB13AGO","Sibling 13 — Age of onset",lavalist=FamAge_list),
    Choice("SIB14MOB","Sibling 14 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB14YOB","Sibling 14 — Birth year",lavalist=FamYOB_list),
    Choice("SIB14AGD","Sibling 14 — Age at death",lavalist=DECAGE_list),
    Choice("SIB14NEU","Sibling 14 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB14PDX","Sibling 14 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB14MOE","Sibling 14 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB14AGO","Sibling 14 — Age of onset",lavalist=FamAge_list),
    Choice("SIB15MOB","Sibling 15 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB15YOB","Sibling 15 — Birth year",lavalist=FamYOB_list),
    Choice("SIB15AGD","Sibling 15 — Age at death",lavalist=DECAGE_list),
    Choice("SIB15NEU","Sibling 15 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB15PDX","Sibling 15 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB15MOE","Sibling 15 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB15AGO","Sibling 15 — Age of onset",lavalist=FamAge_list),
    Choice("SIB16MOB","Sibling 16 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB16YOB","Sibling 16 — Birth year",lavalist=FamYOB_list),
    Choice("SIB16AGD","Sibling 16 — Age at death",lavalist=DECAGE_list),
    Choice("SIB16NEU","Sibling 16 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB16PDX","Sibling 16 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB16MOE","Sibling 16 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB16AGO","Sibling 16 — Age of onset",lavalist=FamAge_list),
    Choice("SIB17MOB","Sibling 17 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB17YOB","Sibling 17 — Birth year",lavalist=FamYOB_list),
    Choice("SIB17AGD","Sibling 17 — Age at death",lavalist=DECAGE_list),
    Choice("SIB17NEU","Sibling 17 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB17PDX","Sibling 17 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB17MOE","Sibling 17 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB17AGO","Sibling 17 — Age of onset",lavalist=FamAge_list),
    Choice("SIB18MOB","Sibling 18 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB18YOB","Sibling 18 — Birth year",lavalist=FamYOB_list),
    Choice("SIB18AGD","Sibling 18 — Age at death",lavalist=DECAGE_list),
    Choice("SIB18NEU","Sibling 18 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB18PDX","Sibling 18 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB18MOE","Sibling 18 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB18AGO","Sibling 18 — Age of onset",lavalist=FamAge_list),
    Choice("SIB19MOB","Sibling 19 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB19YOB","Sibling 19 — Birth year",lavalist=FamYOB_list),
    Choice("SIB19AGD","Sibling 19 — Age at death",lavalist=DECAGE_list),
    Choice("SIB19NEU","Sibling 19 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB19PDX","Sibling 19 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB19MOE","Sibling 19 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB19AGO","Sibling 19 — Age of onset",lavalist=FamAge_list),
    Choice("SIB20MOB","Sibling 20 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("SIB20YOB","Sibling 20 — Birth year",lavalist=FamYOB_list),
    Choice("SIB20AGD","Sibling 20 — Age at death",lavalist=DECAGE_list),
    Choice("SIB20NEU","Sibling 20 — Neurological problem",lavalist=NEURPROB_list),
    Choice("SIB20PDX","Sibling 20 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("SIB20MOE","Sibling 20 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("SIB20AGO","Sibling 20 — Age of onset",lavalist=FamAge_list),
    Choice("KIDS","Number of biological children?",listname="uds3.common.range0_15"),
    Choice("KID1MOB","Child 1 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID1YOB","Child 1 — Birth year",lavalist=FamYOB2_list),
    Choice("KID1AGD","Child 1 — Age at death",lavalist=DECAGE_list),
    Choice("KID1NEU","Child 1 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID1PDX","Child 1 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID1MOE","Child 1 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID1AGO","Child 1 — Age of onset",lavalist=FamAge_list),
    Choice("KID2MOB","Child 2 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID2YOB","Child 2 — Birth year",lavalist=FamYOB2_list),
    Choice("KID2AGD","Child 2 — Age at death",lavalist=DECAGE_list),
    Choice("KID2NEU","Child 2 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID2PDX","Child 2 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID2MOE","Child 2 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID2AGO","Child 2 — Age of onset",lavalist=FamAge_list),
    Choice("KID3MOB","Child 3 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID3YOB","Child 3 — Birth year",lavalist=FamYOB2_list),
    Choice("KID3AGD","Child 3 — Age at death",lavalist=DECAGE_list),
    Choice("KID3NEU","Child 3 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID3PDX","Child 3 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID3MOE","Child 3 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID3AGO","Child 3 — Age of onset",lavalist=FamAge_list),
    Choice("KID4MOB","Child 4 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID4YOB","Child 4 — Birth year",lavalist=FamYOB2_list),
    Choice("KID4AGD","Child 4 — Age at death",lavalist=DECAGE_list),
    Choice("KID4NEU","Child 4 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID4PDX","Child 4 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID4MOE","Child 4 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID4AGO","Child 4 — Age of onset",lavalist=FamAge_list),
    Choice("KID5MOB","Child 5 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID5YOB","Child 5 — Birth year",lavalist=FamYOB2_list),
    Choice("KID5AGD","Child 5 — Age at death",lavalist=DECAGE_list),
    Choice("KID5NEU","Child 5 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID5PDX","Child 5 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID5MOE","Child 5 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID5AGO","Child 5 — Age of onset",lavalist=FamAge_list),
    Choice("KID6MOB","Child 6 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID6YOB","Child 6 — Birth year",lavalist=FamYOB2_list),
    Choice("KID6AGD","Child 6 — Age at death",lavalist=DECAGE_list),
    Choice("KID6NEU","Child 6 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID6PDX","Child 6 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID6MOE","Child 6 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID6AGO","Child 6 — Age of onset",lavalist=FamAge_list),
    Choice("KID7MOB","Child 7 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID7YOB","Child 7 — Birth year",lavalist=FamYOB2_list),
    Choice("KID7AGD","Child 7 — Age at death",lavalist=DECAGE_list),
    Choice("KID7NEU","Child 7 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID7PDX","Child 7 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID7MOE","Child 7 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID7AGO","Child 7 — Age of onset",lavalist=FamAge_list),
    Choice("KID8MOB","Child 8 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID8YOB","Child 8 — Birth year",lavalist=FamYOB2_list),
    Choice("KID8AGD","Child 8 — Age at death",lavalist=DECAGE_list),
    Choice("KID8NEU","Child 8 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID8PDX","Child 8 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID8MOE","Child 8 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID8AGO","Child 8 — Age of onset",lavalist=FamAge_list),
    Choice("KID9MOB","Child 9 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID9YOB","Child 9 — Birth year",lavalist=FamYOB2_list),
    Choice("KID9AGD","Child 9 — Age at death",lavalist=DECAGE_list),
    Choice("KID9NEU","Child 9 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID9PDX","Child 9 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID9MOE","Child 9 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID9AGO","Child 9 — Age of onset",lavalist=FamAge_list),
    Choice("KID10MOB","Child 10 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID10YOB","Child 10 — Birth year",lavalist=FamYOB2_list),
    Choice("KID10AGD","Child 10 — Age at death",lavalist=DECAGE_list),
    Choice("KID10NEU","Child 10 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID10PDX","Child 10 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID10MOE","Child 10 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID10AGO","Child 10 — Age of onset",lavalist=FamAge_list),
    Choice("KID11MOB","Child 11 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID11YOB","Child 11 — Birth year",lavalist=FamYOB2_list),
    Choice("KID11AGD","Child 11 — Age at death",lavalist=DECAGE_list),
    Choice("KID11NEU","Child 11 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID11PDX","Child 11 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID11MOE","Child 11 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID11AGO","Child 11 — Age of onset",lavalist=FamAge_list),
    Choice("KID12MOB","Child 12 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID12YOB","Child 12 — Birth year",lavalist=FamYOB2_list),
    Choice("KID12AGD","Child 12 — Age at death",lavalist=DECAGE_list),
    Choice("KID12NEU","Child 12 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID12PDX","Child 12 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID12MOE","Child 12 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID12AGO","Child 12 — Age of onset",lavalist=FamAge_list),
    Choice("KID13MOB","Child 13 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID13YOB","Child 13 — Birth year",lavalist=FamYOB2_list),
    Choice("KID13AGD","Child 13 — Age at death",lavalist=DECAGE_list),
    Choice("KID13NEU","Child 13 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID13PDX","Child 13 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID13MOE","Child 13 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID13AGO","Child 13 — Age of onset",lavalist=FamAge_list),
    Choice("KID14MOB","Child 14 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID14YOB","Child 14 — Birth year",lavalist=FamYOB2_list),
    Choice("KID14AGD","Child 14 — Age at death",lavalist=DECAGE_list),
    Choice("KID14NEU","Child 14 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID14PDX","Child 14 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID14MOE","Child 14 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID14AGO","Child 14 — Age of onset",lavalist=FamAge_list),
    Choice("KID15MOB","Child 15 — Birth month",listname="uds3.udsinformantdemo3.INBIRMO"),
    Choice("KID15YOB","Child 15 — Birth year",lavalist=FamYOB2_list),
    Choice("KID15AGD","Child 15 — Age at death",lavalist=DECAGE_list),
    Choice("KID15NEU","Child 15 — Neurological problem",lavalist=NEURPROB_list),
    Choice("KID15PDX","Child 15 — Primary diagnosis",lavalist=PrimDx_list),
    Choice("KID15MOE","Child 15 — Method of evaluation",lavalist=EvalMethod_list),
    Choice("KID15AGO","Child 15 — Age of onset",lavalist=FamAge_list),
]

UDSFamilyHistory3=Instrument(fullname,jname,tname,columns)
