
DELETE from viewproperty where instance='lava' and scope='crms-nacc' and entity='udsformchecklist3';

INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.a2Sub','en','lava','crms-nacc',NULL,'udsformchecklist3','a2Sub','Form Checklist','r','scale','No','',NULL,NULL,7,0,'','uds.noYes01',NULL,1,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.a2Not','en','lava','crms-nacc',NULL,'udsformchecklist3','a2Not','Form Checklist','r','scale','No','',NULL,NULL,20,0,'','uds.z1Reason',NULL,2,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.a2Comm','en','lava','crms-nacc',NULL,'udsformchecklist3','a2Comm','Form Checklist','i','string','No','',NULL,NULL,20,0,'onkeypress="UDS_onlyNaccCharactersAllowed(event)"','',NULL,3,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.a3Sub','en','lava','crms-nacc',NULL,'udsformchecklist3','a3Sub','Form Checklist','r','scale','No','',NULL,NULL,7,0,'','uds.noYes01',NULL,4,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.a3Not','en','lava','crms-nacc',NULL,'udsformchecklist3','a3Not','Form Checklist','r','scale','No','',NULL,NULL,20,0,'','uds.z1Reason',NULL,5,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.a3Comm','en','lava','crms-nacc',NULL,'udsformchecklist3','a3Comm','Form Checklist','i','string','No','',NULL,NULL,20,0,'onkeypress="UDS_onlyNaccCharactersAllowed(event)"','',NULL,6,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.a4Sub','en','lava','crms-nacc',NULL,'udsformchecklist3','a4Sub','Form Checklist','r','scale','No','',NULL,NULL,7,0,'','uds.noYes01',NULL,7,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.a4Not','en','lava','crms-nacc',NULL,'udsformchecklist3','a4Not','Form Checklist','r','scale','No','',NULL,NULL,20,0,'','uds.z1Reason',NULL,8,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.a4Comm','en','lava','crms-nacc',NULL,'udsformchecklist3','a4Comm','Form Checklist','i','string','No','',NULL,NULL,20,0,'onkeypress="UDS_onlyNaccCharactersAllowed(event)"','',NULL,9,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.b1Sub','en','lava','crms-nacc',NULL,'udsformchecklist3','b1Sub','Form Checklist','r','scale','No','',NULL,NULL,7,0,'','uds.noYes01',NULL,10,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.b1Not','en','lava','crms-nacc',NULL,'udsformchecklist3','b1Not','Form Checklist','r','scale','No','',NULL,NULL,20,0,'','uds.z1Reason',NULL,11,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.b1Comm','en','lava','crms-nacc',NULL,'udsformchecklist3','b1Comm','Form Checklist','i','string','No','',NULL,NULL,20,0,'onkeypress="UDS_onlyNaccCharactersAllowed(event)"','',NULL,12,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.b5Sub','en','lava','crms-nacc',NULL,'udsformchecklist3','b5Sub','Form Checklist','r','scale','No','',NULL,NULL,7,0,'','uds.noYes01',NULL,13,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.b5Not','en','lava','crms-nacc',NULL,'udsformchecklist3','b5Not','Form Checklist','r','scale','No','',NULL,NULL,20,0,'','uds.z1Reason',NULL,14,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.b5Comm','en','lava','crms-nacc',NULL,'udsformchecklist3','b5Comm','Form Checklist','i','string','No','',NULL,NULL,20,0,'onkeypress="UDS_onlyNaccCharactersAllowed(event)"','',NULL,15,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.b6Sub','en','lava','crms-nacc',NULL,'udsformchecklist3','b6Sub','Form Checklist','r','scale','No','',NULL,NULL,7,0,'','uds.noYes01',NULL,16,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.b6Not','en','lava','crms-nacc',NULL,'udsformchecklist3','b6Not','Form Checklist','r','scale','No','',NULL,NULL,20,0,'','uds.z1Reason',NULL,17,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.b6Comm','en','lava','crms-nacc',NULL,'udsformchecklist3','b6Comm','Form Checklist','i','string','No','',NULL,NULL,20,0,'onkeypress="UDS_onlyNaccCharactersAllowed(event)"','',NULL,18,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.b7Sub','en','lava','crms-nacc',NULL,'udsformchecklist3','b7Sub','Form Checklist','r','scale','No','',NULL,NULL,7,0,'','uds.noYes01',NULL,19,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.b7Not','en','lava','crms-nacc',NULL,'udsformchecklist3','b7Not','Form Checklist','r','scale','No','',NULL,NULL,20,0,'','uds.z1Reason',NULL,20,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.udsformchecklist3.b7Comm','en','lava','crms-nacc',NULL,'udsformchecklist3','b7Comm','Form Checklist','i','string','No','',NULL,NULL,20,0,'onkeypress="UDS_onlyNaccCharactersAllowed(event)"','',NULL,21,'','2009-01-24 21:28:51');
